// Copyright (c) 2026 Jonathan Embley-Riches. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// --- LEGAL DISCLAIMER ---
// UnrealRoboticsLab is an independent software plugin. It is NOT affiliated with,
// endorsed by, or sponsored by Epic Games, Inc. "Unreal" and "Unreal Engine" are
// trademarks or registered trademarks of Epic Games, Inc. in the US and elsewhere.
//
// This plugin incorporates third-party software: MuJoCo (Apache 2.0),
// CoACD (MIT), and libzmq (MPL 2.0). See ThirdPartyNotices.txt for details.

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"
#include "Tests/MjTestHelpers.h"
#include "MuJoCo/Components/Actuators/MjActuator.h"
#include "MuJoCo/Core/MjArticulation.h"
#include <mujoco/mujoco.h>

namespace MjSuctionModelTestsLocal
{
inline int32 FindIdBySuffixLocal(const mjModel* M, mjtObj Type, int32 Count, const TCHAR* Name)
{
	const FString Want(Name);
	for (int32 i = 0; i < Count; ++i)
	{
		const char* Nm = mj_id2name(const_cast<mjModel*>(M), Type, i);
		if (Nm && FString(UTF8_TO_TCHAR(Nm)).EndsWith(Want))
			return i;
	}
	return -1;
}
} // namespace MjSuctionModelTestsLocal

// URLab.Suction.ModelVariant — the cup variant imports+compiles: adhesion
// actuator present and typed, cup_site resolves, the 10 drive actuators are
// intact, and the finger linkage is gone.
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMjSuctionModelVariant,
	"URLab.Suction.ModelVariant",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)
bool FMjSuctionModelVariant::RunTest(const FString&)
{
	using namespace MjSuctionModelTestsLocal;
	const FString XmlPath = FPaths::Combine(FPaths::ProjectPluginsDir(),
		TEXT("UnrealRoboticsLab/Scripts/mink_golden/models/stanford_tidybot/tidybot_suction_ue.xml"));
	if (!FPaths::FileExists(XmlPath))
	{
		AddError(TEXT("suction variant missing"));
		return false;
	}
	FMjXmlImportSession S;
	if (!S.InitFromFile(XmlPath) || !S.Compile())
	{
		AddError(S.LastError);
		S.Cleanup();
		return false;
	}
	mjModel* M = S.Model();

	TestTrue(TEXT("cup_site resolves"),
		FindIdBySuffixLocal(M, mjOBJ_SITE, M->nsite, TEXT("cup_site")) >= 0);
	TestTrue(TEXT("suction actuator resolves"),
		FindIdBySuffixLocal(M, mjOBJ_ACTUATOR, M->nu, TEXT("suction")) >= 0);
	TestTrue(TEXT("fingers gone"),
		FindIdBySuffixLocal(M, mjOBJ_ACTUATOR, M->nu, TEXT("fingers_actuator")) < 0);
	TestEqual(TEXT("11 actuators (10 drive + suction)"), (int32)M->nu, 11);
	// Typed adhesion component generated by the importer:
	bool bAdhesionTyped = false;
	for (UMjActuator* A : S.Robot->GetActuators())
		if (A && A->Type == EMjActuatorType::Adhesion)
		{
			bAdhesionTyped = true;
			break;
		}
	TestTrue(TEXT("UMjAdhesionActuator typed component present"), bAdhesionTyped);
	S.Cleanup();
	return true;
}

// URLab.Suction.PickAsset — the affordance-annotated free body imports.
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMjSuctionPickAsset,
	"URLab.Suction.PickAsset",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)
bool FMjSuctionPickAsset::RunTest(const FString&)
{
	using namespace MjSuctionModelTestsLocal;
	const FString XmlPath = FPaths::Combine(FPaths::ProjectPluginsDir(),
		TEXT("UnrealRoboticsLab/Scripts/demos/assets/suction_box.xml"));
	if (!FPaths::FileExists(XmlPath))
	{
		AddError(TEXT("suction_box asset missing"));
		return false;
	}
	FMjXmlImportSession S;
	if (!S.InitFromFile(XmlPath) || !S.Compile())
	{
		AddError(S.LastError);
		S.Cleanup();
		return false;
	}
	mjModel* M = S.Model();
	TestTrue(TEXT("affordance site resolves"),
		FindIdBySuffixLocal(M, mjOBJ_SITE, M->nsite, TEXT("affordance_suction_top")) >= 0);
	TestTrue(TEXT("free joint present"), M->njnt >= 1 && M->jnt_type[0] == mjJNT_FREE);
	S.Cleanup();
	return true;
}
